--- # Configuration Port
server:
  port: 8081

--- # Configuration Thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false

--- # Configuration Devtools
spring:
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: false

--- # Configuration MariaDb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot
    username: boot
    password: boot

# Configuration mybatis

# mybatis.mapper
#-locations=classpath:sqlmap/**/*.xml
#
# mybatis.configuration.map
#-underscore
#-to
#-camel
#-case=true